/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author carol_flgngfy
 */
public class Jugar extends javax.swing.JFrame {

    /**
     * Creates new form Jugar
     */
    public Jugar() {
        initComponents();
         tbtCuadriculas.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0; // Hacer la altura de las pestañas cero para ocultarlas
            }
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreJugador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbtCuadriculas = new javax.swing.JTabbedPane();
        panel3x3 = new javax.swing.JPanel();
        panel4x4 = new javax.swing.JPanel();
        panel4x5 = new javax.swing.JPanel();
        panel4x6 = new javax.swing.JPanel();
        panel4x7 = new javax.swing.JPanel();
        panel4x8 = new javax.swing.JPanel();
        panel4x9 = new javax.swing.JPanel();
        panel4x10 = new javax.swing.JPanel();
        pnlDigitosIzq = new javax.swing.JPanel();
        botonRedondo2 = new Componentes.BotonRedondo();
        pnlDigitosDer = new javax.swing.JPanel();
        botonRedondo3 = new Componentes.BotonRedondo();
        btnBorrarJugada = new Componentes.BotonRedondo();
        btnRehacerJugada = new Componentes.BotonRedondo();
        btnBorrarJuego = new Componentes.BotonRedondo();
        btnTerminarJuego = new Componentes.BotonRedondo();
        btnGuardarJuego = new Componentes.BotonRedondo();
        btnCargarJuego = new Componentes.BotonRedondo();
        btnJugar = new Componentes.BotonRedondo();
        panelTiempo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FUTOSHIKI");

        txtNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del jugador");

        panel3x3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel3x3Layout = new javax.swing.GroupLayout(panel3x3);
        panel3x3.setLayout(panel3x3Layout);
        panel3x3Layout.setHorizontalGroup(
            panel3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel3x3Layout.setVerticalGroup(
            panel3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("3x3", panel3x3);

        panel4x4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x4Layout = new javax.swing.GroupLayout(panel4x4);
        panel4x4.setLayout(panel4x4Layout);
        panel4x4Layout.setHorizontalGroup(
            panel4x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x4Layout.setVerticalGroup(
            panel4x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("4x4", panel4x4);

        panel4x5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x5Layout = new javax.swing.GroupLayout(panel4x5);
        panel4x5.setLayout(panel4x5Layout);
        panel4x5Layout.setHorizontalGroup(
            panel4x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x5Layout.setVerticalGroup(
            panel4x5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("5x5", panel4x5);

        panel4x6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x6Layout = new javax.swing.GroupLayout(panel4x6);
        panel4x6.setLayout(panel4x6Layout);
        panel4x6Layout.setHorizontalGroup(
            panel4x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x6Layout.setVerticalGroup(
            panel4x6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("6x6", panel4x6);

        panel4x7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x7Layout = new javax.swing.GroupLayout(panel4x7);
        panel4x7.setLayout(panel4x7Layout);
        panel4x7Layout.setHorizontalGroup(
            panel4x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x7Layout.setVerticalGroup(
            panel4x7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("7x7", panel4x7);

        panel4x8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x8Layout = new javax.swing.GroupLayout(panel4x8);
        panel4x8.setLayout(panel4x8Layout);
        panel4x8Layout.setHorizontalGroup(
            panel4x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x8Layout.setVerticalGroup(
            panel4x8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("8x8", panel4x8);

        panel4x9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x9Layout = new javax.swing.GroupLayout(panel4x9);
        panel4x9.setLayout(panel4x9Layout);
        panel4x9Layout.setHorizontalGroup(
            panel4x9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x9Layout.setVerticalGroup(
            panel4x9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("9x9", panel4x9);

        panel4x10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel4x10Layout = new javax.swing.GroupLayout(panel4x10);
        panel4x10.setLayout(panel4x10Layout);
        panel4x10Layout.setHorizontalGroup(
            panel4x10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        panel4x10Layout.setVerticalGroup(
            panel4x10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        tbtCuadriculas.addTab("10x10", panel4x10);

        pnlDigitosIzq.setBackground(new java.awt.Color(0, 51, 51));

        botonRedondo2.setBackground(new java.awt.Color(255, 255, 255));
        botonRedondo2.setBorder(null);
        botonRedondo2.setForeground(new java.awt.Color(0, 0, 0));
        botonRedondo2.setText("1");
        botonRedondo2.setColor1(new java.awt.Color(255, 255, 255));
        botonRedondo2.setColor2(new java.awt.Color(255, 255, 255));
        botonRedondo2.setColor3(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDigitosIzqLayout = new javax.swing.GroupLayout(pnlDigitosIzq);
        pnlDigitosIzq.setLayout(pnlDigitosIzqLayout);
        pnlDigitosIzqLayout.setHorizontalGroup(
            pnlDigitosIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDigitosIzqLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(botonRedondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDigitosIzqLayout.setVerticalGroup(
            pnlDigitosIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDigitosIzqLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonRedondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        pnlDigitosDer.setBackground(new java.awt.Color(0, 51, 51));

        botonRedondo3.setBackground(new java.awt.Color(255, 255, 255));
        botonRedondo3.setBorder(null);
        botonRedondo3.setForeground(new java.awt.Color(0, 0, 0));
        botonRedondo3.setText("1");
        botonRedondo3.setColor1(new java.awt.Color(255, 255, 255));
        botonRedondo3.setColor2(new java.awt.Color(255, 255, 255));
        botonRedondo3.setColor3(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDigitosDerLayout = new javax.swing.GroupLayout(pnlDigitosDer);
        pnlDigitosDer.setLayout(pnlDigitosDerLayout);
        pnlDigitosDerLayout.setHorizontalGroup(
            pnlDigitosDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDigitosDerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRedondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDigitosDerLayout.setVerticalGroup(
            pnlDigitosDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDigitosDerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonRedondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        btnBorrarJugada.setBackground(new java.awt.Color(204, 204, 0));
        btnBorrarJugada.setText("Borrar Jugada");
        btnBorrarJugada.setColor1(new java.awt.Color(204, 204, 0));
        btnBorrarJugada.setColor2(new java.awt.Color(204, 204, 0));
        btnBorrarJugada.setColor3(new java.awt.Color(204, 204, 0));

        btnRehacerJugada.setBackground(new java.awt.Color(153, 51, 255));
        btnRehacerJugada.setText("Rehacer Jugada");
        btnRehacerJugada.setToolTipText("");
        btnRehacerJugada.setColor1(new java.awt.Color(153, 51, 255));
        btnRehacerJugada.setColor2(new java.awt.Color(153, 51, 255));
        btnRehacerJugada.setColor3(new java.awt.Color(153, 51, 255));

        btnBorrarJuego.setBackground(new java.awt.Color(102, 102, 255));
        btnBorrarJuego.setText("Borrar Juego");
        btnBorrarJuego.setColor1(new java.awt.Color(102, 102, 255));
        btnBorrarJuego.setColor2(new java.awt.Color(102, 102, 255));
        btnBorrarJuego.setColor3(new java.awt.Color(102, 102, 255));

        btnTerminarJuego.setBackground(new java.awt.Color(0, 51, 102));
        btnTerminarJuego.setText("Terminar Juego");
        btnTerminarJuego.setColor1(new java.awt.Color(0, 51, 102));
        btnTerminarJuego.setColor2(new java.awt.Color(0, 51, 102));
        btnTerminarJuego.setColor3(new java.awt.Color(0, 51, 102));

        btnGuardarJuego.setBackground(new java.awt.Color(255, 102, 102));
        btnGuardarJuego.setText("Guardar Juego");
        btnGuardarJuego.setColor1(new java.awt.Color(255, 102, 102));
        btnGuardarJuego.setColor2(new java.awt.Color(255, 102, 102));
        btnGuardarJuego.setColor3(new java.awt.Color(255, 102, 102));

        btnCargarJuego.setBackground(new java.awt.Color(51, 204, 255));
        btnCargarJuego.setText("Cargar Juego");
        btnCargarJuego.setColor1(new java.awt.Color(51, 204, 255));
        btnCargarJuego.setColor2(new java.awt.Color(51, 204, 255));
        btnCargarJuego.setColor3(new java.awt.Color(51, 204, 255));

        btnJugar.setBackground(new java.awt.Color(255, 153, 0));
        btnJugar.setText("Jugar");
        btnJugar.setColor1(new java.awt.Color(255, 153, 0));
        btnJugar.setColor2(new java.awt.Color(255, 153, 0));
        btnJugar.setColor3(new java.awt.Color(255, 153, 0));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        panelTiempo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Minutos");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Horas");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Segundos");
        jLabel5.setToolTipText("");

        txtHoras.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtHoras.setForeground(new java.awt.Color(0, 0, 0));
        txtHoras.setText("0");

        txtMinutos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtMinutos.setForeground(new java.awt.Color(0, 0, 0));
        txtMinutos.setText("0");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("0");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout panelTiempoLayout = new javax.swing.GroupLayout(panelTiempo);
        panelTiempo.setLayout(panelTiempoLayout);
        panelTiempoLayout.setHorizontalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiempoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtHoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMinutos))
                .addGap(33, 33, 33)
                .addGroup(panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17))
        );
        panelTiempoLayout.setVerticalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoras)
                    .addComponent(txtMinutos)
                    .addComponent(jLabel8))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pnlDigitosIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbtCuadriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDigitosDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBorrarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnBorrarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRehacerJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTerminarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtCuadriculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDigitosDer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDigitosIzq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRehacerJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTerminarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        tbtCuadriculas.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    private void botonRedondo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRedondo6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonRedondo botonRedondo2;
    private Componentes.BotonRedondo botonRedondo3;
    public Componentes.BotonRedondo btnBorrarJuego;
    public Componentes.BotonRedondo btnBorrarJugada;
    public Componentes.BotonRedondo btnCargarJuego;
    public Componentes.BotonRedondo btnGuardarJuego;
    public Componentes.BotonRedondo btnJugar;
    public Componentes.BotonRedondo btnRehacerJugada;
    public Componentes.BotonRedondo btnTerminarJuego;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel3x3;
    private javax.swing.JPanel panel4x10;
    private javax.swing.JPanel panel4x4;
    private javax.swing.JPanel panel4x5;
    private javax.swing.JPanel panel4x6;
    private javax.swing.JPanel panel4x7;
    private javax.swing.JPanel panel4x8;
    private javax.swing.JPanel panel4x9;
    private javax.swing.JPanel panelTiempo;
    public javax.swing.JPanel pnlDigitosDer;
    public javax.swing.JPanel pnlDigitosIzq;
    private javax.swing.JTabbedPane tbtCuadriculas;
    public javax.swing.JLabel txtHoras;
    public javax.swing.JLabel txtMinutos;
    private javax.swing.JTextField txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
