/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Dilan
 */
public class MenuConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form MenuConfiguracion
     */
    public MenuConfiguracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesTamaño = new javax.swing.ButtonGroup();
        botonesNivel = new javax.swing.ButtonGroup();
        botonesMultinivel = new javax.swing.ButtonGroup();
        botonesReloj = new javax.swing.ButtonGroup();
        botonesVentana = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRegistrarse = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreRegistrarse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPinRegistrarse = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoRegistrarse = new javax.swing.JTextField();
        btnCancelarRegistrarse = new Componentes.BotonRedondo();
        btnRegistrarseRegistrarse = new Componentes.BotonRedondo();
        panelConfiguracion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabConfig = new javax.swing.JTabbedPane();
        tabTamaño = new javax.swing.JPanel();
        btn3x3 = new javax.swing.JRadioButton();
        btn4x4 = new javax.swing.JRadioButton();
        btn5x5 = new javax.swing.JRadioButton();
        btn6x6 = new javax.swing.JRadioButton();
        btn7x7 = new javax.swing.JRadioButton();
        btn8x8 = new javax.swing.JRadioButton();
        btn9x9 = new javax.swing.JRadioButton();
        btn10x10 = new javax.swing.JRadioButton();
        tabNivelJuego = new javax.swing.JPanel();
        btnFacil = new javax.swing.JRadioButton();
        btnIntermedio = new javax.swing.JRadioButton();
        btnDificil = new javax.swing.JRadioButton();
        tabMultinivel = new javax.swing.JPanel();
        btnSiMultinivel = new javax.swing.JRadioButton();
        btnNoMultinivel = new javax.swing.JRadioButton();
        tabReloj = new javax.swing.JPanel();
        btnCronometro = new javax.swing.JRadioButton();
        btnNoReloj = new javax.swing.JRadioButton();
        btnTemporizador = new javax.swing.JRadioButton();
        spinnerMins = new javax.swing.JSpinner();
        spinnerHoras = new javax.swing.JSpinner();
        spinnerSegs = new javax.swing.JSpinner();
        lblHoras = new javax.swing.JLabel();
        lblMins = new javax.swing.JLabel();
        lblSegs = new javax.swing.JLabel();
        tabPosicion = new javax.swing.JPanel();
        btnDerecha = new javax.swing.JRadioButton();
        btnIzquierda = new javax.swing.JRadioButton();
        tabNombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JPasswordField();
        btnOlvidePin = new Componentes.BotonRedondo();
        btnRegistrarse = new Componentes.BotonRedondo();
        btnCambiarPin = new Componentes.BotonRedondo();
        btnGuardar = new Componentes.BotonRedondo();
        btnCancelar = new Componentes.BotonRedondo();
        panelOlvidePin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreCorreo = new javax.swing.JTextField();
        btnEnviarCorreo = new Componentes.BotonRedondo();
        btnCancelarCorreo = new Componentes.BotonRedondo();
        panelCambiarPin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreCambiar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCancelarCambiar = new Componentes.BotonRedondo();
        btnCambiarCambiar = new Componentes.BotonRedondo();
        txtPinActualCambiar = new javax.swing.JPasswordField();
        txtNuevoPinCambiar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        panelRegistrarse.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Registrarse");

        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("Nombre:");

        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("PIN:");

        jLabel8.setForeground(new java.awt.Color(204, 102, 0));
        jLabel8.setText("Correo electrónico:");

        btnCancelarRegistrarse.setText("Cancelar");
        btnCancelarRegistrarse.setColor1(new java.awt.Color(255, 0, 0));
        btnCancelarRegistrarse.setColor2(new java.awt.Color(255, 0, 0));
        btnCancelarRegistrarse.setColor3(new java.awt.Color(255, 0, 0));

        btnRegistrarseRegistrarse.setText("Registrarse");
        btnRegistrarseRegistrarse.setColor1(new java.awt.Color(102, 255, 0));
        btnRegistrarseRegistrarse.setColor2(new java.awt.Color(102, 255, 0));
        btnRegistrarseRegistrarse.setColor3(new java.awt.Color(102, 255, 0));
        btnRegistrarseRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseRegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarseLayout = new javax.swing.GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addComponent(btnCancelarRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnRegistrarseRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtCorreoRegistrarse)
                            .addComponent(txtPinRegistrarse)
                            .addComponent(txtNombreRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        panelRegistrarseLayout.setVerticalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPinRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtCorreoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarseRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        panelConfiguracion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Configuración");

        tabConfig.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        tabTamaño.setBackground(new java.awt.Color(255, 255, 255));

        btn3x3.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn3x3);
        btn3x3.setForeground(new java.awt.Color(204, 102, 0));
        btn3x3.setText("3x3");
        btn3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3x3ActionPerformed(evt);
            }
        });

        btn4x4.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn4x4);
        btn4x4.setForeground(new java.awt.Color(204, 102, 0));
        btn4x4.setText("4x4");
        btn4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4x4ActionPerformed(evt);
            }
        });

        btn5x5.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn5x5);
        btn5x5.setForeground(new java.awt.Color(204, 102, 0));
        btn5x5.setText("5x5");

        btn6x6.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn6x6);
        btn6x6.setForeground(new java.awt.Color(204, 102, 0));
        btn6x6.setText("6x6");

        btn7x7.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn7x7);
        btn7x7.setForeground(new java.awt.Color(204, 102, 0));
        btn7x7.setText("7x7");
        btn7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7x7ActionPerformed(evt);
            }
        });

        btn8x8.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn8x8);
        btn8x8.setForeground(new java.awt.Color(204, 102, 0));
        btn8x8.setText("8x8");
        btn8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8x8ActionPerformed(evt);
            }
        });

        btn9x9.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn9x9);
        btn9x9.setForeground(new java.awt.Color(204, 102, 0));
        btn9x9.setText("9x9");

        btn10x10.setBackground(new java.awt.Color(255, 255, 255));
        botonesTamaño.add(btn10x10);
        btn10x10.setForeground(new java.awt.Color(204, 102, 0));
        btn10x10.setText("10x10");

        javax.swing.GroupLayout tabTamañoLayout = new javax.swing.GroupLayout(tabTamaño);
        tabTamaño.setLayout(tabTamañoLayout);
        tabTamañoLayout.setHorizontalGroup(
            tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTamañoLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3x3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn5x5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn4x4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10x10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9x9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        tabTamañoLayout.setVerticalGroup(
            tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTamañoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7x7)
                    .addComponent(btn3x3))
                .addGap(35, 35, 35)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4x4)
                    .addComponent(btn8x8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5x5)
                    .addComponent(btn9x9))
                .addGap(40, 40, 40)
                .addGroup(tabTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6x6)
                    .addComponent(btn10x10))
                .addGap(38, 38, 38))
        );

        tabConfig.addTab("Tamaño de la cuadricula", tabTamaño);

        tabNivelJuego.setBackground(new java.awt.Color(255, 255, 255));

        btnFacil.setBackground(new java.awt.Color(255, 255, 255));
        botonesNivel.add(btnFacil);
        btnFacil.setForeground(new java.awt.Color(204, 102, 0));
        btnFacil.setText("Facil");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });

        btnIntermedio.setBackground(new java.awt.Color(255, 255, 255));
        botonesNivel.add(btnIntermedio);
        btnIntermedio.setForeground(new java.awt.Color(204, 102, 0));
        btnIntermedio.setText("Intermedio");
        btnIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntermedioActionPerformed(evt);
            }
        });

        btnDificil.setBackground(new java.awt.Color(255, 255, 255));
        botonesNivel.add(btnDificil);
        btnDificil.setForeground(new java.awt.Color(204, 102, 0));
        btnDificil.setText("Dificil");

        javax.swing.GroupLayout tabNivelJuegoLayout = new javax.swing.GroupLayout(tabNivelJuego);
        tabNivelJuego.setLayout(tabNivelJuegoLayout);
        tabNivelJuegoLayout.setHorizontalGroup(
            tabNivelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNivelJuegoLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(tabNivelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        tabNivelJuegoLayout.setVerticalGroup(
            tabNivelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNivelJuegoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnFacil)
                .addGap(31, 31, 31)
                .addComponent(btnIntermedio)
                .addGap(30, 30, 30)
                .addComponent(btnDificil)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabConfig.addTab("Nivel del juego", tabNivelJuego);

        tabMultinivel.setBackground(new java.awt.Color(255, 255, 255));

        btnSiMultinivel.setBackground(new java.awt.Color(255, 255, 255));
        botonesMultinivel.add(btnSiMultinivel);
        btnSiMultinivel.setForeground(new java.awt.Color(204, 102, 0));
        btnSiMultinivel.setText("Si");

        btnNoMultinivel.setBackground(new java.awt.Color(255, 255, 255));
        botonesMultinivel.add(btnNoMultinivel);
        btnNoMultinivel.setForeground(new java.awt.Color(204, 102, 0));
        btnNoMultinivel.setText("No");

        javax.swing.GroupLayout tabMultinivelLayout = new javax.swing.GroupLayout(tabMultinivel);
        tabMultinivel.setLayout(tabMultinivelLayout);
        tabMultinivelLayout.setHorizontalGroup(
            tabMultinivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMultinivelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(tabMultinivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNoMultinivel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiMultinivel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        tabMultinivelLayout.setVerticalGroup(
            tabMultinivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMultinivelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnSiMultinivel)
                .addGap(53, 53, 53)
                .addComponent(btnNoMultinivel)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tabConfig.addTab("Multinivel", tabMultinivel);

        tabReloj.setBackground(new java.awt.Color(255, 255, 255));

        btnCronometro.setBackground(new java.awt.Color(255, 255, 255));
        botonesReloj.add(btnCronometro);
        btnCronometro.setForeground(new java.awt.Color(204, 102, 0));
        btnCronometro.setText("Cronómetro");
        btnCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCronometroActionPerformed(evt);
            }
        });

        btnNoReloj.setBackground(new java.awt.Color(255, 255, 255));
        botonesReloj.add(btnNoReloj);
        btnNoReloj.setForeground(new java.awt.Color(204, 102, 0));
        btnNoReloj.setText("No");
        btnNoReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoRelojActionPerformed(evt);
            }
        });

        btnTemporizador.setBackground(new java.awt.Color(255, 255, 255));
        botonesReloj.add(btnTemporizador);
        btnTemporizador.setForeground(new java.awt.Color(204, 102, 0));
        btnTemporizador.setText("Temporizador");
        btnTemporizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemporizadorActionPerformed(evt);
            }
        });

        lblHoras.setForeground(new java.awt.Color(204, 102, 0));
        lblHoras.setText("Horas");

        lblMins.setForeground(new java.awt.Color(204, 102, 0));
        lblMins.setText("Mins.");

        lblSegs.setForeground(new java.awt.Color(204, 102, 0));
        lblSegs.setText("Segs.");

        javax.swing.GroupLayout tabRelojLayout = new javax.swing.GroupLayout(tabReloj);
        tabReloj.setLayout(tabRelojLayout);
        tabRelojLayout.setHorizontalGroup(
            tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabRelojLayout.createSequentialGroup()
                .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabRelojLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNoReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabRelojLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnTemporizador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(spinnerMins)
                        .addComponent(spinnerSegs)
                        .addComponent(spinnerHoras)))
                .addGap(51, 51, 51))
        );
        tabRelojLayout.setVerticalGroup(
            tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRelojLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCronometro)
                    .addComponent(spinnerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblMins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoReloj)
                    .addComponent(spinnerMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblSegs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemporizador)
                    .addComponent(spinnerSegs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        tabConfig.addTab("Uso del reloj", tabReloj);

        tabPosicion.setBackground(new java.awt.Color(255, 255, 255));

        btnDerecha.setBackground(new java.awt.Color(255, 255, 255));
        botonesVentana.add(btnDerecha);
        btnDerecha.setForeground(new java.awt.Color(204, 102, 0));
        btnDerecha.setText("Derecha");

        btnIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        botonesVentana.add(btnIzquierda);
        btnIzquierda.setForeground(new java.awt.Color(204, 102, 0));
        btnIzquierda.setText("Izquierda");

        javax.swing.GroupLayout tabPosicionLayout = new javax.swing.GroupLayout(tabPosicion);
        tabPosicion.setLayout(tabPosicionLayout);
        tabPosicionLayout.setHorizontalGroup(
            tabPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPosicionLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(tabPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        tabPosicionLayout.setVerticalGroup(
            tabPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPosicionLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnDerecha)
                .addGap(47, 47, 47)
                .addComponent(btnIzquierda)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        tabConfig.addTab("Posición de la ventana", tabPosicion);

        tabNombre.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setForeground(new java.awt.Color(204, 102, 0));

        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Escriba su nombre:");

        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("PIN:");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Si el nombre no está en uso, debe de registrarse");

        txtPIN.setBackground(new java.awt.Color(204, 204, 204));

        btnOlvidePin.setText("Olvide mi PIN");
        btnOlvidePin.setColor1(new java.awt.Color(204, 102, 0));
        btnOlvidePin.setColor2(new java.awt.Color(204, 102, 0));
        btnOlvidePin.setColor3(new java.awt.Color(204, 102, 0));

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setColor1(new java.awt.Color(0, 204, 255));
        btnRegistrarse.setColor2(new java.awt.Color(0, 204, 255));
        btnRegistrarse.setColor3(new java.awt.Color(0, 204, 255));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnCambiarPin.setText("Cambiar PIN");
        btnCambiarPin.setColor1(new java.awt.Color(153, 0, 255));
        btnCambiarPin.setColor2(new java.awt.Color(153, 0, 255));
        btnCambiarPin.setColor3(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout tabNombreLayout = new javax.swing.GroupLayout(tabNombre);
        tabNombre.setLayout(tabNombreLayout);
        tabNombreLayout.setHorizontalGroup(
            tabNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabNombreLayout.createSequentialGroup()
                .addComponent(btnCambiarPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOlvidePin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        tabNombreLayout.setVerticalGroup(
            tabNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNombreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(tabNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOlvidePin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabConfig.addTab("Nombre del jugador", tabNombre);

        btnGuardar.setText("Guardar cambios");
        btnGuardar.setColor1(new java.awt.Color(102, 255, 0));
        btnGuardar.setColor2(new java.awt.Color(102, 255, 0));
        btnGuardar.setColor3(new java.awt.Color(102, 255, 0));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setColor1(new java.awt.Color(255, 0, 0));
        btnCancelar.setColor2(new java.awt.Color(255, 0, 0));
        btnCancelar.setColor3(new java.awt.Color(255, 0, 0));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(tabConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelOlvidePin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Cascadia Mono", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 102, 0));
        jLabel9.setText("Olvide mi PIN");

        jLabel10.setForeground(new java.awt.Color(204, 102, 0));
        jLabel10.setText("Nombre del jugador a recuperar:");

        txtNombreCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCorreoActionPerformed(evt);
            }
        });

        btnEnviarCorreo.setText("Enviar correo de recuperación");
        btnEnviarCorreo.setColor1(new java.awt.Color(102, 255, 0));
        btnEnviarCorreo.setColor2(new java.awt.Color(102, 255, 0));
        btnEnviarCorreo.setColor3(new java.awt.Color(102, 255, 0));

        btnCancelarCorreo.setText("Cancelar");
        btnCancelarCorreo.setColor1(new java.awt.Color(255, 0, 0));
        btnCancelarCorreo.setColor2(new java.awt.Color(255, 0, 0));
        btnCancelarCorreo.setColor3(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelOlvidePinLayout = new javax.swing.GroupLayout(panelOlvidePin);
        panelOlvidePin.setLayout(panelOlvidePinLayout);
        panelOlvidePinLayout.setHorizontalGroup(
            panelOlvidePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlvidePinLayout.createSequentialGroup()
                .addGroup(panelOlvidePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOlvidePinLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel10))
                    .addGroup(panelOlvidePinLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panelOlvidePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOlvidePinLayout.createSequentialGroup()
                                .addComponent(btnCancelarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnEnviarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)))
                    .addGroup(panelOlvidePinLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(txtNombreCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panelOlvidePinLayout.setVerticalGroup(
            panelOlvidePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOlvidePinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtNombreCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(panelOlvidePinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        panelCambiarPin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Cascadia Mono", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 102, 0));
        jLabel11.setText("Cambiar mi PIN");

        jLabel12.setForeground(new java.awt.Color(204, 102, 0));
        jLabel12.setText("Nombre:");

        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("PIN actual:");

        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("Nuevo PIN:");

        btnCancelarCambiar.setText("Cancelar");
        btnCancelarCambiar.setColor1(new java.awt.Color(255, 0, 0));
        btnCancelarCambiar.setColor2(new java.awt.Color(255, 0, 0));
        btnCancelarCambiar.setColor3(new java.awt.Color(255, 0, 0));
        btnCancelarCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCambiarActionPerformed(evt);
            }
        });

        btnCambiarCambiar.setText("Cambiar PIN");
        btnCambiarCambiar.setColor1(new java.awt.Color(0, 255, 0));
        btnCambiarCambiar.setColor2(new java.awt.Color(0, 255, 0));
        btnCambiarCambiar.setColor3(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout panelCambiarPinLayout = new javax.swing.GroupLayout(panelCambiarPin);
        panelCambiarPin.setLayout(panelCambiarPinLayout);
        panelCambiarPinLayout.setHorizontalGroup(
            panelCambiarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarPinLayout.createSequentialGroup()
                .addGroup(panelCambiarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarPinLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel11))
                    .addGroup(panelCambiarPinLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnCancelarCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnCambiarCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCambiarPinLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(panelCambiarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCambiar)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(txtPinActualCambiar)
                            .addComponent(txtNuevoPinCambiar, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelCambiarPinLayout.setVerticalGroup(
            panelCambiarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarPinLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtPinActualCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(txtNuevoPinCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(panelCambiarPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelOlvidePin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCambiarPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelOlvidePin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCambiarPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnTemporizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemporizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTemporizadorActionPerformed

    private void btnNoRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoRelojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoRelojActionPerformed

    private void btnCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCronometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCronometroActionPerformed

    private void btnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIntermedioActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btn8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8x8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8x8ActionPerformed

    private void btn4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4x4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4x4ActionPerformed

    private void btn3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3x3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3x3ActionPerformed

    private void btn7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7x7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7x7ActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnRegistrarseRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseRegistrarseActionPerformed

    private void txtNombreCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCorreoActionPerformed

    private void btnCancelarCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesMultinivel;
    private javax.swing.ButtonGroup botonesNivel;
    private javax.swing.ButtonGroup botonesReloj;
    private javax.swing.ButtonGroup botonesTamaño;
    private javax.swing.ButtonGroup botonesVentana;
    public javax.swing.JRadioButton btn10x10;
    public javax.swing.JRadioButton btn3x3;
    public javax.swing.JRadioButton btn4x4;
    public javax.swing.JRadioButton btn5x5;
    public javax.swing.JRadioButton btn6x6;
    public javax.swing.JRadioButton btn7x7;
    public javax.swing.JRadioButton btn8x8;
    public javax.swing.JRadioButton btn9x9;
    public Componentes.BotonRedondo btnCambiarCambiar;
    public Componentes.BotonRedondo btnCambiarPin;
    public Componentes.BotonRedondo btnCancelar;
    public Componentes.BotonRedondo btnCancelarCambiar;
    public Componentes.BotonRedondo btnCancelarCorreo;
    public Componentes.BotonRedondo btnCancelarRegistrarse;
    public javax.swing.JRadioButton btnCronometro;
    public javax.swing.JRadioButton btnDerecha;
    public javax.swing.JRadioButton btnDificil;
    public Componentes.BotonRedondo btnEnviarCorreo;
    public javax.swing.JRadioButton btnFacil;
    public Componentes.BotonRedondo btnGuardar;
    public javax.swing.JRadioButton btnIntermedio;
    public javax.swing.JRadioButton btnIzquierda;
    public javax.swing.JRadioButton btnNoMultinivel;
    public javax.swing.JRadioButton btnNoReloj;
    public Componentes.BotonRedondo btnOlvidePin;
    public Componentes.BotonRedondo btnRegistrarse;
    public Componentes.BotonRedondo btnRegistrarseRegistrarse;
    public javax.swing.JRadioButton btnSiMultinivel;
    public javax.swing.JRadioButton btnTemporizador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblHoras;
    public javax.swing.JLabel lblMins;
    public javax.swing.JLabel lblSegs;
    public javax.swing.JPanel panelCambiarPin;
    public javax.swing.JPanel panelConfiguracion;
    public javax.swing.JPanel panelOlvidePin;
    public javax.swing.JPanel panelRegistrarse;
    public javax.swing.JSpinner spinnerHoras;
    public javax.swing.JSpinner spinnerMins;
    public javax.swing.JSpinner spinnerSegs;
    public javax.swing.JTabbedPane tabConfig;
    private javax.swing.JPanel tabMultinivel;
    private javax.swing.JPanel tabNivelJuego;
    private javax.swing.JPanel tabNombre;
    private javax.swing.JPanel tabPosicion;
    private javax.swing.JPanel tabReloj;
    private javax.swing.JPanel tabTamaño;
    public javax.swing.JTextField txtCorreoRegistrarse;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreCambiar;
    public javax.swing.JTextField txtNombreCorreo;
    public javax.swing.JTextField txtNombreRegistrarse;
    public javax.swing.JPasswordField txtNuevoPinCambiar;
    public javax.swing.JPasswordField txtPIN;
    public javax.swing.JPasswordField txtPinActualCambiar;
    public javax.swing.JPasswordField txtPinRegistrarse;
    // End of variables declaration//GEN-END:variables
}
